DELETE http://localhost:3001/api/blogs/9
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhYWthLUFyc2thIiwiaWQiOjEsImlhdCI6MTY2ODI4MzExNn0.27_hJEogvCIIcrHMXEpcAg9gx0VFHgPHTl8XVRITse8
