POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyc2thQG9zb2l0ZS5jb20iLCJpZCI6MSwiaWF0IjoxNjY4MzMwNTgxfQ.9U7L10MvZZCw7lRkA-NQHORDdYz2Ra7YwwATMmQSr_c

{
  "author": "jaska", "url": "ranenblogi.com", "title": "Ranenblogi-2", "year": 2099
}